before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: ndtAHq/7Lmtqy0tc/cX9/JDEXk376kVPPnD28eKzIS236YVvInjRiGNetjt7fsL8ClqzpCUxSwsZuyR46QBs+Fqd+RyHMR9SkR9uYSs33UXEy5GUGg2wOrLi9KhJTA8dj5+3CkpVadF22o/1zKjXmdhtbLSuCt3+4u7tKdtptjfv47lTow3dWX+ioH+Ns5Zm3ZA/v2YiZ2b7fJBCgUUfeY3oaWmgvNFgO7wQSeEp3YI2aq/23/jlF0IIuV28tX4dFz/o2QCLwrtp7NswAHSfxaPi6RmE1bzozAqshbhbzgFj/a7RA5zy9OiaYOtbEBC3myMIXe6nzQBXD9jKFXCUkx2TD/N6JWjD3L+eDTmIq+9qZER064UIz5sxSK5cAhRqAQ3MPCoM0SLGGE1gIi6LkjlJIp/RejUiCzkRHCmFARV4ke2hqbCT1t6U2/ryKJC7GhBFFRujD6KfP6fs/ExHJgHCWPil4OCvq84FXLkdnIBf7dTAPe+vywlYRIgIsuw/SE0WshdRzF6ef9OyjP2xcfTDtP6lviAtKMgMs4gDasfHZjnb8TxzJ6Eqs4sUE+HGIT+wmWSPygVKVtgxtNOdRlvAe/IzwzL3rMpRw9SrmB4WEieOtSKAA192NaJLMx+nG1GfRfk1p/1s40fmKxSG9a7KSW0Zodc+S11TlkMZ2hQ= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
